// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWcalMmmNEDtmRnBSjmIViccw4bUp5DOc',
    appId: '1:173097778841:web:232eb226a869a17edc8208',
    messagingSenderId: '173097778841',
    projectId: 'mealmatch-ec825',
    authDomain: 'mealmatch-ec825.firebaseapp.com',
    storageBucket: 'mealmatch-ec825.firebasestorage.app',
    measurementId: 'G-JEW02ZTPY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBijuzEiqHpjUhskNZCOpGjvMApcjPjVBw',
    appId: '1:173097778841:android:b817db6cdfb63deedc8208',
    messagingSenderId: '173097778841',
    projectId: 'mealmatch-ec825',
    storageBucket: 'mealmatch-ec825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXoPocmD679cDL1tFDyD267BwUiP_Nqg',
    appId: '1:173097778841:ios:b4dd138be727fcaddc8208',
    messagingSenderId: '173097778841',
    projectId: 'mealmatch-ec825',
    storageBucket: 'mealmatch-ec825.firebasestorage.app',
    iosBundleId: 'com.example.mealmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXoPocmD679cDL1tFDyD267BwUiP_Nqg',
    appId: '1:173097778841:ios:b4dd138be727fcaddc8208',
    messagingSenderId: '173097778841',
    projectId: 'mealmatch-ec825',
    storageBucket: 'mealmatch-ec825.firebasestorage.app',
    iosBundleId: 'com.example.mealmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWcalMmmNEDtmRnBSjmIViccw4bUp5DOc',
    appId: '1:173097778841:web:883242235e737424dc8208',
    messagingSenderId: '173097778841',
    projectId: 'mealmatch-ec825',
    authDomain: 'mealmatch-ec825.firebaseapp.com',
    storageBucket: 'mealmatch-ec825.firebasestorage.app',
    measurementId: 'G-BD2GMKLPGM',
  );
}
